-- ByteStreams Customer Portal — Supabase Schema
-- Target project: mxhyvvgjtqllohpvrwon (dev) / klzznfagrtormretqsgb (prod)
-- Run in Supabase SQL editor

-- ── businesses ──────────────────────────────────────────────────────────────
-- Generic business entity decoupled from any product-specific table.
-- DialTone restaurants optionally link via dialtone_location_id.
CREATE TABLE IF NOT EXISTS businesses (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name                    text NOT NULL,
  logo_url                text,
  business_type           text NOT NULL DEFAULT 'restaurant',
  dialtone_location_id    uuid,   -- → DialTone restaurant.id (nullable)
  monthly_amount_cents    integer NOT NULL DEFAULT 9900,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

-- ── portal_accounts ─────────────────────────────────────────────────────────
-- One row per user. Admin creates this first; operator activates via invite link.
CREATE TABLE IF NOT EXISTS portal_accounts (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id    uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  email           text UNIQUE NOT NULL,
  full_name       text,
  business_id     uuid REFERENCES businesses(id) ON DELETE SET NULL,
  product         text NOT NULL DEFAULT 'dialtone',  -- 'dialtone' | 'future_saas'
  role            text NOT NULL DEFAULT 'owner',     -- 'owner' | 'staff' | 'admin'
  status          text NOT NULL DEFAULT 'setup_pending', -- 'setup_pending' | 'active' | 'churned'
  is_admin        boolean NOT NULL DEFAULT false,
  invited_at      timestamptz,
  activated_at    timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ── billing_schedule ────────────────────────────────────────────────────────
-- One row per business per billing month. Generated by Worker cron on the 1st.
CREATE TABLE IF NOT EXISTS billing_schedule (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id               uuid NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  product                   text NOT NULL DEFAULT 'dialtone',
  billing_month             date NOT NULL,          -- first day of the month
  amount_cents              integer NOT NULL,
  due_date                  date NOT NULL,          -- typically billing_month + 14 days
  status                    text NOT NULL DEFAULT 'pending', -- 'pending' | 'paid' | 'overdue'
  stripe_payment_intent_id  text,
  paid_at                   timestamptz,
  created_at                timestamptz NOT NULL DEFAULT now(),
  UNIQUE (business_id, billing_month, product)
);

-- ── billing_notifications ───────────────────────────────────────────────────
-- Tracks every notification sent (email or portal) per billing record.
CREATE TABLE IF NOT EXISTS billing_notifications (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  billing_id  uuid NOT NULL REFERENCES billing_schedule(id) ON DELETE CASCADE,
  type        text NOT NULL,  -- 'invoice_ready' | 'payment_due' | 'overdue' | 'payment_received'
  channel     text NOT NULL DEFAULT 'email',  -- 'email' | 'portal'
  recipient   text,           -- email address notified
  sent_at     timestamptz NOT NULL DEFAULT now(),
  opened_at   timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── portal_messages ─────────────────────────────────────────────────────────
-- Admin-authored messages shown on the portal dashboard.
-- business_id NULL = general (shown to all); non-null = customer-specific.
CREATE TABLE IF NOT EXISTS portal_messages (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id uuid REFERENCES businesses(id) ON DELETE CASCADE,
  body        text NOT NULL,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_portal_accounts_email       ON portal_accounts (email);
CREATE INDEX IF NOT EXISTS idx_portal_accounts_business    ON portal_accounts (business_id);
CREATE INDEX IF NOT EXISTS idx_portal_accounts_auth_user   ON portal_accounts (auth_user_id);
CREATE INDEX IF NOT EXISTS idx_billing_schedule_business   ON billing_schedule (business_id, billing_month DESC);
CREATE INDEX IF NOT EXISTS idx_billing_notif_billing       ON billing_notifications (billing_id);
CREATE INDEX IF NOT EXISTS idx_portal_messages_business    ON portal_messages (business_id, is_active);

-- ── updated_at triggers ──────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_businesses_updated_at
  BEFORE UPDATE ON businesses
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_portal_accounts_updated_at
  BEFORE UPDATE ON portal_accounts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── Row Level Security ───────────────────────────────────────────────────────
ALTER TABLE businesses            ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_accounts       ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_schedule      ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_messages       ENABLE ROW LEVEL SECURITY;

-- Helper: resolve business_id for the calling auth user
CREATE OR REPLACE FUNCTION my_business_id()
RETURNS uuid AS $$
  SELECT business_id FROM portal_accounts WHERE auth_user_id = auth.uid() LIMIT 1;
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- businesses: owner/staff read their own business
CREATE POLICY "business_read_own" ON businesses
  FOR SELECT USING (id = my_business_id());

-- portal_accounts: user reads their own row
CREATE POLICY "account_read_own" ON portal_accounts
  FOR SELECT USING (auth_user_id = auth.uid());

-- billing_schedule: read own business bills
CREATE POLICY "billing_read_own" ON billing_schedule
  FOR SELECT USING (business_id = my_business_id());

-- billing_notifications: read own business notifications
CREATE POLICY "notif_read_own" ON billing_notifications
  FOR SELECT USING (business_id = my_business_id());

-- portal_messages: read general messages or own-business messages
CREATE POLICY "messages_read_own" ON portal_messages
  FOR SELECT USING (business_id IS NULL OR business_id = my_business_id());

-- Service role bypasses RLS (used by the Worker API with service role key)

-- ── Supabase Auth: restrict portal sign-ups ──────────────────────────────────
-- Disable public sign-ups in Supabase dashboard:
--   Authentication > Settings > Disable "Enable email signups"
-- Only admin-generated invite links (magic link OTP) should work.
